# -*- coding: utf-8 -*-
"""likeabiltiy_model.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1l3i65LPI36ItvSGK2iI2GcHzDBUnjx7N
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np
import re

# .txt 파일에서 데이터 불러오기
def load_data(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        data = file.read()
    return data

# GRU 모델 불러오기
model = tf.keras.models.load_model('likeabiliyt_gru.h5')

# 텍스트 전처리
def preprocess_text(text):
    text_cleaned = re.sub(r"[^가-힣A-Za-z0-9]", " ", text)
    tokenizer = Tokenizer(num_words=10000)
    tokenizer.fit_on_texts([text_cleaned])
    sequence = tokenizer.texts_to_sequences([text_cleaned])
    padded_sequence = pad_sequences(sequence, maxlen=100)
    return padded_sequence

# 호감도 추론
def predict_likeability(text):
    preprocessed_text = preprocess_text(text)
    predictions = model.predict(preprocessed_text)
    return np.argmax(predictions, axis=-1)

# 호감도 추론 실행
likeability_score = predict_likeability(text_data)

# 결과 출력
likeability_labels = ['0%', '25%', '50%', '75%', '100%']
print(f"호감도: {likeability_labels[likeability_score[0]]}")